// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package influxdb

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)
	// // InfluxDBHost is named INFLUXDB_HOST and needs to be
	// // provided by the user.
	// InfluxDBHost string `json:"INFLUXDB_HOST" validate:"required"`
	// // InfluxDBToken is named INFLUXDB_TOKEN and needs to be
	// // provided by the user.
	// InfluxDBToken string `json:"INFLUXDB_TOKEN" validate:"required"`

	// // InfluxDBDatabase is named INFLUXDB_DATABASE and needs to be
	// // provided by the user.
	// InfluxDBDatabase string `json:"INFLUXDB_DATABASE" validate:"required"`
func (DestinationConfig) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"destinationConfigParam": {
			Default:     "yes",
			Description: "destinationConfigParam must be either yes or no (defaults to yes).",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"yes", "no"}},
			},
		},
		"INFLUXDB_HOST": {
			Default:     "",
			Description: "InfluxDBHost is named INFLUXDB_HOST and needs to be provided by teh user",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"INFLUXDB_TOKEN": {
			Default:     "",
			Description: "InfluxDBToken is named INFLUXDB_TOKEN and needs to be provided by teh user",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"INFLUXDB_DATABASE": {
			Default:     "",
			Description: "InfluxDBDatabase is named INFLUXDB_DATABASE and needs to be provided by teh user",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},	
	}
}
